/*
 * Created on 29 lug 2016 ( Time 14:37:00 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.mf.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "categorieaccept"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="categorieaccept", catalog="torneo" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CategorieacceptEntity.countAll", query="SELECT COUNT(x) FROM CategorieacceptEntity x" )
} )
public class CategorieacceptEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	// "torneoId" (column "torneo_id") is not defined by itself because used as FK in a link 
	// "categorieId" (column "categorie_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="categorie_id", referencedColumnName="id")
    private CategorieEntity categorie   ;

    @ManyToOne
    @JoinColumn(name="torneo_id", referencedColumnName="id")
    private TorneoEntity torneo      ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CategorieacceptEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setCategorie( CategorieEntity categorie ) {
        this.categorie = categorie;
    }
    public CategorieEntity getCategorie() {
        return this.categorie;
    }

    public void setTorneo( TorneoEntity torneo ) {
        this.torneo = torneo;
    }
    public TorneoEntity getTorneo() {
        return this.torneo;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
