/*
 * Created on 29 lug 2016 ( Time 14:37:00 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.mf.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "friend"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="friend", catalog="torneo" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="FriendEntity.countAll", query="SELECT COUNT(x) FROM FriendEntity x" )
} )
public class FriendEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.DATE)
    @Column(name="sentInvitation")
    private Date       sentinvitation ;

	// "torneoId" (column "torneo_id") is not defined by itself because used as FK in a link 
	// "host" (column "host") is not defined by itself because used as FK in a link 
	// "guest" (column "guest") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="guest", referencedColumnName="id")
    private SocietaEntity societaGuest     ;

    @ManyToOne
    @JoinColumn(name="torneo_id", referencedColumnName="id")
    private TorneoEntity torneo      ;

    @ManyToOne
    @JoinColumn(name="host", referencedColumnName="id")
    private SocietaEntity societaHost     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public FriendEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : sentInvitation ( DATE ) 
    public void setSentinvitation( Date sentinvitation ) {
        this.sentinvitation = sentinvitation;
    }
    public Date getSentinvitation() {
        return this.sentinvitation;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setSocietaGuest( SocietaEntity societaGuest ) {
        this.societaGuest = societaGuest;
    }
    public SocietaEntity getSocietGuest() {
        return this.societaGuest;
    }

    public void setTorneo( TorneoEntity torneo ) {
        this.torneo = torneo;
    }
    public TorneoEntity getTorneo() {
        return this.torneo;
    }

    public void setSocieta( SocietaEntity societaHost ) {
        this.societaHost = societaHost;
    }
    public SocietaEntity getSocietaHost() {
        return this.societaHost;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(sentinvitation);
        return sb.toString(); 
    } 

}
