/*
 * Created on 29 lug 2016 ( Time 14:37:00 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.mf.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "passwordresettoken"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="passwordresettoken", catalog="torneo" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PasswordresettokenEntity.countAll", query="SELECT COUNT(x) FROM PasswordresettokenEntity x" )
} )
public class PasswordresettokenEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expiryDate")
    private Date       expirydate   ;

    @Column(name="token", length=255)
    private String     token        ;

	// "userId" (column "user_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id")
    private UserAccountEntity userAccount ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PasswordresettokenEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : expiryDate ( DATETIME ) 
    public void setExpirydate( Date expirydate ) {
        this.expirydate = expirydate;
    }
    public Date getExpirydate() {
        return this.expirydate;
    }

    //--- DATABASE MAPPING : token ( VARCHAR ) 
    public void setToken( String token ) {
        this.token = token;
    }
    public String getToken() {
        return this.token;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setUserAccount( UserAccountEntity userAccount ) {
        this.userAccount = userAccount;
    }
    public UserAccountEntity getUserAccount() {
        return this.userAccount;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(expirydate);
        sb.append("|");
        sb.append(token);
        return sb.toString(); 
    } 

}
