
/*
 * Created on 22 lug 2016 ( Time 17:15:33 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.mock;

import java.util.LinkedList;
import java.util.List;

import org.mf.bean.jpa.CategorieEntity;
import org.mf.test.MockValues;

public class CategorieEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public CategorieEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}

	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public CategorieEntity createInstance( Integer id ) {
		CategorieEntity entity = createNewInstance();
		// Init Primary Key fields
		entity.setId( id) ;
		return entity ;
	}

	/**
	 * Creates an instance without Primary Key
	 * @param id1
	 * @return
	 */
	public CategorieEntity createNewInstance() {
		CategorieEntity entity = new CategorieEntity();
		// Init Data fields
		entity.setCategoria( mockValues.nextString(30) ) ; // java.lang.String 
		entity.setAnnomin( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setAnnomax( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setPunti( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setPuntimax( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setNrset( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setNote( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setActive( mockValues.nextBoolean() ) ; // java.lang.Boolean 
		entity.setCategoriecol( mockValues.nextString(45) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfIscrizioni( TODO ) ; // List<Iscrizioni> 
		// setListOfCategorieaccept( TODO ) ; // List<Categorieaccept> 
		return entity ;
	}

	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<CategorieEntity> createList(int count) {
		List<CategorieEntity> list = new LinkedList<CategorieEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
