/*
 * Created on 21 lug 2016 ( Time 13:31:08 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.web.listitem;

import org.mf.bean.Categorie;
import org.mf.web.common.ListItem;

public class CategorieListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public CategorieListItem(Categorie categorie) {
		super();

		this.value = ""
			 + (categorie != null ? categorie.getId() : "")
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = (categorie != null ? categorie.toString() : "--");
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
