/*
 * Created on 8 set 2016 ( Time 16:09:31 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.business.service;

import java.util.List;

import org.mf.bean.Categorie;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Business Service Interface for entity Categorie.
 */
public interface CategorieService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Categorie findById(Integer id) ;

	/**
	 * Load the page request.
	 * @return Page
	 */
	Page<Categorie> findAll(Pageable pageRequest);

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Categorie> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Categorie save(Categorie entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Categorie update(Categorie entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Categorie create(Categorie entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete(Integer id);

	/**
	 * 
	 * @return total entity count
	 */
	Long count();
}
