/*
 * Created on 29 lug 2016 ( Time 11:50:30 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.test.persistence;

import org.mf.bean.jpa.CategorieEntity;
import org.mf.configuration.ConfigurationTest;
import org.mf.configuration.JPAConfTest;
import org.mf.mock.CategorieEntityMock;
import org.mf.data.repository.jpa.CategorieJpaRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

/**
 * JUnit test case for Categorie persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = { ConfigurationTest.class, JPAConfTest.class })
public class CategoriePersistenceTest {

	@Autowired
	private CategorieJpaRepository service; 

	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
//		CategoriePersistence service = PersistenceServiceProvider.getService(CategoriePersistence.class);
		System.out.println("CountAll = " + service.count() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Categorie persistence : delete + load ..." );
		
//		CategorieJpaRepository service = PersistenceServiceProvider.getService(CategorieJpaRepository.class);
		
		CategorieEntityMock mock = new CategorieEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0 );
		// process( service, mock, ... );
	}

	private void process(CategorieJpaRepository service, CategorieEntityMock mock, Integer id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		CategorieEntity entity = service.findOne( id );
		if ( entity != null ) {
			// Found
			System.out.println("   FOUND : " + entity );

			// Save (update) with the same values to avoid database integrity errors
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found
			System.out.println("   NOT FOUND" );
			// Create a new instance
			entity = mock.createNewInstance();
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.save(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			service.delete(entity.getId());
			System.out.println("   deleted = " + entity);
		}		
	}
}
