/*
 * Created on 1 ago 2016 ( Time 15:51:03 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Categorie implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 30 )
    private String categoria;


    private Integer annomin;


    private Integer annomax;


    private Integer punti;


    private Integer puntimax;


    private Integer nrset;

    @Size( max = 255 )
    private String note;

    @NotNull
    private Boolean active;

    @Size( max = 45 )
    private String categoriecol;


    public Categorie() {
    };

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCategoria( String categoria ) {
        this.categoria = categoria;
    }
    public String getCategoria() {
        return this.categoria;
    }
    public void setAnnomin( Integer annomin ) {
        this.annomin = annomin;
    }
    public Integer getAnnomin() {
        return this.annomin;
    }
    public void setAnnomax( Integer annomax ) {
        this.annomax = annomax;
    }
    public Integer getAnnomax() {
        return this.annomax;
    }
    public void setPunti( Integer punti ) {
        this.punti = punti;
    }
    public Integer getPunti() {
        return this.punti;
    }
    public void setPuntimax( Integer puntimax ) {
        this.puntimax = puntimax;
    }
    public Integer getPuntimax() {
        return this.puntimax;
    }
    public void setNrset( Integer nrset ) {
        this.nrset = nrset;
    }
    public Integer getNrset() {
        return this.nrset;
    }
    public void setNote( String note ) {
        this.note = note;
    }
    public String getNote() {
        return this.note;
    }
    public void setActive( Boolean active ) {
        this.active = active;
    }
    public Boolean getActive() {
        return this.active;
    }
    public void setCategoriecol( String categoriecol ) {
        this.categoriecol = categoriecol;
    }
    public String getCategoriecol() {
        return this.categoriecol;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(categoria);
        sb.append("|");
        sb.append(annomin);
        sb.append("|");
        sb.append(annomax);
        sb.append("|");
        sb.append(punti);
        sb.append("|");
        sb.append(puntimax);
        sb.append("|");
        sb.append(nrset);
        sb.append("|");
        sb.append(note);
        sb.append("|");
        sb.append(active);
        sb.append("|");
        sb.append(categoriecol);
        return sb.toString(); 
    } 

}
