/*
 * Created on 29 lug 2016 ( Time 14:37:00 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Gironi implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 30 )
    private String descrizione;


    private Integer teamnr;


    private Integer playtime;


    private Integer campo;


    private Integer livello;


    private Integer eliminatorie;


    private Integer perdente;

    @NotNull
    private Integer iscrizioniId;


    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDescrizione( String descrizione ) {
        this.descrizione = descrizione;
    }
    public String getDescrizione() {
        return this.descrizione;
    }
    public void setTeamnr( Integer teamnr ) {
        this.teamnr = teamnr;
    }
    public Integer getTeamnr() {
        return this.teamnr;
    }
    public void setPlaytime( Integer playtime ) {
        this.playtime = playtime;
    }
    public Integer getPlaytime() {
        return this.playtime;
    }
    public void setCampo( Integer campo ) {
        this.campo = campo;
    }
    public Integer getCampo() {
        return this.campo;
    }
    public void setLivello( Integer livello ) {
        this.livello = livello;
    }
    public Integer getLivello() {
        return this.livello;
    }
    public void setEliminatorie( Integer eliminatorie ) {
        this.eliminatorie = eliminatorie;
    }
    public Integer getEliminatorie() {
        return this.eliminatorie;
    }
    public void setPerdente( Integer perdente ) {
        this.perdente = perdente;
    }
    public Integer getPerdente() {
        return this.perdente;
    }
    public void setIscrizioniId( Integer iscrizioniId ) {
        this.iscrizioniId = iscrizioniId;
    }
    public Integer getIscrizioniId() {
        return this.iscrizioniId;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(descrizione);
        sb.append("|");
        sb.append(teamnr);
        sb.append("|");
        sb.append(playtime);
        sb.append("|");
        sb.append(campo);
        sb.append("|");
        sb.append(livello);
        sb.append("|");
        sb.append(eliminatorie);
        sb.append("|");
        sb.append(perdente);
        sb.append("|");
        sb.append(iscrizioniId);
        return sb.toString(); 
    } 

}
