/*
 * Created on 29 lug 2016 ( Time 14:37:00 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Match implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer teamA;


    private Short punti1teamA;


    private Short punti2teamA;

    @NotNull
    private Integer teamB;


    private Short punti1teamB;


    private Short punti2teamB;

    @Size( max = 40 )
    private String campo;

    @Size( max = 40 )
    private String arbitro;


    private Date inizio;

    @NotNull
    private Short progressivo;

    @NotNull
    private Integer gironiId;


    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setTeamA( Integer teamA ) {
        this.teamA = teamA;
    }
    public Integer getTeamA() {
        return this.teamA;
    }
    public void setPunti1teamA( Short punti1teamA ) {
        this.punti1teamA = punti1teamA;
    }
    public Short getPunti1teamA() {
        return this.punti1teamA;
    }
    public void setPunti2teamA( Short punti2teamA ) {
        this.punti2teamA = punti2teamA;
    }
    public Short getPunti2teamA() {
        return this.punti2teamA;
    }
    public void setTeamB( Integer teamB ) {
        this.teamB = teamB;
    }
    public Integer getTeamB() {
        return this.teamB;
    }
    public void setPunti1teamB( Short punti1teamB ) {
        this.punti1teamB = punti1teamB;
    }
    public Short getPunti1teamB() {
        return this.punti1teamB;
    }
    public void setPunti2teamB( Short punti2teamB ) {
        this.punti2teamB = punti2teamB;
    }
    public Short getPunti2teamB() {
        return this.punti2teamB;
    }
    public void setCampo( String campo ) {
        this.campo = campo;
    }
    public String getCampo() {
        return this.campo;
    }
    public void setArbitro( String arbitro ) {
        this.arbitro = arbitro;
    }
    public String getArbitro() {
        return this.arbitro;
    }
    public void setInizio( Date inizio ) {
        this.inizio = inizio;
    }
    public Date getInizio() {
        return this.inizio;
    }
    public void setProgressivo( Short progressivo ) {
        this.progressivo = progressivo;
    }
    public Short getProgressivo() {
        return this.progressivo;
    }
    public void setGironiId( Integer gironiId ) {
        this.gironiId = gironiId;
    }
    public Integer getGironiId() {
        return this.gironiId;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(teamA);
        sb.append("|");
        sb.append(punti1teamA);
        sb.append("|");
        sb.append(punti2teamA);
        sb.append("|");
        sb.append(teamB);
        sb.append("|");
        sb.append(punti1teamB);
        sb.append("|");
        sb.append(punti2teamB);
        sb.append("|");
        sb.append(campo);
        sb.append("|");
        sb.append(arbitro);
        sb.append("|");
        sb.append(inizio);
        sb.append("|");
        sb.append(progressivo);
        sb.append("|");
        sb.append(gironiId);
        return sb.toString(); 
    } 

}
