/*
 * Created on 29 lug 2016 ( Time 14:37:00 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Societa implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 50 )
    private String nome;

    @Size( max = 50 )
    private String responsabile;

    @Size( max = 50 )
    private String via;


    private Integer cap;

    @Size( max = 50 )
    private String citta;

    @Size( max = 5 )
    private String provincia;

    @Size( max = 50 )
    private String nazione;

    @Size( max = 30 )
    private String tel;

    @Size( max = 30 )
    private String fax;

    @Size( max = 30 )
    private String cellulare;

    @Size( max = 30 )
    private String email;

    @Size( max = 30 )
    private String url;

    @Size( max = 45 )
    private String logo;

    @NotNull
    private Long userAccountId;


    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNome( String nome ) {
        this.nome = nome;
    }
    public String getNome() {
        return this.nome;
    }
    public void setResponsabile( String responsabile ) {
        this.responsabile = responsabile;
    }
    public String getResponsabile() {
        return this.responsabile;
    }
    public void setVia( String via ) {
        this.via = via;
    }
    public String getVia() {
        return this.via;
    }
    public void setCap( Integer cap ) {
        this.cap = cap;
    }
    public Integer getCap() {
        return this.cap;
    }
    public void setCitta( String citta ) {
        this.citta = citta;
    }
    public String getCitta() {
        return this.citta;
    }
    public void setProvincia( String provincia ) {
        this.provincia = provincia;
    }
    public String getProvincia() {
        return this.provincia;
    }
    public void setNazione( String nazione ) {
        this.nazione = nazione;
    }
    public String getNazione() {
        return this.nazione;
    }
    public void setTel( String tel ) {
        this.tel = tel;
    }
    public String getTel() {
        return this.tel;
    }
    public void setFax( String fax ) {
        this.fax = fax;
    }
    public String getFax() {
        return this.fax;
    }
    public void setCellulare( String cellulare ) {
        this.cellulare = cellulare;
    }
    public String getCellulare() {
        return this.cellulare;
    }
    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }
    public void setUrl( String url ) {
        this.url = url;
    }
    public String getUrl() {
        return this.url;
    }
    public void setLogo( String logo ) {
        this.logo = logo;
    }
    public String getLogo() {
        return this.logo;
    }
    public void setUserAccountId( Long userAccountId ) {
        this.userAccountId = userAccountId;
    }
    public Long getUserAccountId() {
        return this.userAccountId;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(nome);
        sb.append("|");
        sb.append(responsabile);
        sb.append("|");
        sb.append(via);
        sb.append("|");
        sb.append(cap);
        sb.append("|");
        sb.append(citta);
        sb.append("|");
        sb.append(provincia);
        sb.append("|");
        sb.append(nazione);
        sb.append("|");
        sb.append(tel);
        sb.append("|");
        sb.append(fax);
        sb.append("|");
        sb.append(cellulare);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(url);
        sb.append("|");
        sb.append(logo);
        sb.append("|");
        sb.append(userAccountId);
        return sb.toString(); 
    } 

}
