/*
 * Created on 1 ago 2016 ( Time 15:51:03 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Torneo implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer societamgrId;

    @Size( max = 45 )
    private String descrizione;

    @NotNull
    private Date inizio;

    @NotNull
    private Date aperturaiscrizioni;

    @NotNull
    private Date chiusuraiscrizioni;

    @Size( max = 2147483647 )
    private String note;

    @Size( max = 45 )
    private String luogo;


    public Torneo() {
    };

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setSocietamgrId( Integer societamgrId ) {
        this.societamgrId = societamgrId;
    }
    public Integer getSocietamgrId() {
        return this.societamgrId;
    }
    public void setDescrizione( String descrizione ) {
        this.descrizione = descrizione;
    }
    public String getDescrizione() {
        return this.descrizione;
    }
    public void setInizio( Date inizio ) {
        this.inizio = inizio;
    }
    public Date getInizio() {
        return this.inizio;
    }
    public void setAperturaiscrizioni( Date aperturaiscrizioni ) {
        this.aperturaiscrizioni = aperturaiscrizioni;
    }
    public Date getAperturaiscrizioni() {
        return this.aperturaiscrizioni;
    }
    public void setChiusuraiscrizioni( Date chiusuraiscrizioni ) {
        this.chiusuraiscrizioni = chiusuraiscrizioni;
    }
    public Date getChiusuraiscrizioni() {
        return this.chiusuraiscrizioni;
    }
    public void setNote( String note ) {
        this.note = note;
    }
    public String getNote() {
        return this.note;
    }
    public void setLuogo( String luogo ) {
        this.luogo = luogo;
    }
    public String getLuogo() {
        return this.luogo;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(societamgrId);
        sb.append("|");
        sb.append(descrizione);
        sb.append("|");
        sb.append(inizio);
        sb.append("|");
        sb.append(aperturaiscrizioni);
        sb.append("|");
        sb.append(chiusuraiscrizioni);
        // attribute 'note' not usable (type = String Long Text)
        sb.append("|");
        sb.append(luogo);
        return sb.toString(); 
    } 

}
