/*
 * Created on 29 lug 2016 ( Time 14:37:01 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Verificationtoken implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Date expirydate;

    @Size( max = 255 )
    private String token;

    @NotNull
    private Long userId;


    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setExpirydate( Date expirydate ) {
        this.expirydate = expirydate;
    }
    public Date getExpirydate() {
        return this.expirydate;
    }
    public void setToken( String token ) {
        this.token = token;
    }
    public String getToken() {
        return this.token;
    }
    public void setUserId( Long userId ) {
        this.userId = userId;
    }
    public Long getUserId() {
        return this.userId;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(expirydate);
        sb.append("|");
        sb.append(token);
        sb.append("|");
        sb.append(userId);
        return sb.toString(); 
    } 

}
